# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acb7ecb12fc57a1d5c1f96e1ee1e81e7eecf8e4db2a8d3bfb5608af0383c21dbdbbdf931ac37ea91260da87519e2494553c7171152db5ab97ab973a2a7ad039a

test:
  secret_key_base: 881ea8500a17d315c27de6a31beb7d18fc5d4ef95a4ce56b592b0b668b1041b88fb07e3b91e1bad007f070ed21977e505f74c515f1a7ddf32f60cfeb42a18afa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
